<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ScanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('scans')->truncate();

        $merchantMapping = [
            1 => 'ryglP6rtAF8us9',
            2 => 'ibniBjwDk6Hr6b',
            3 => 'xcg3UU1xImQ4Wj',
            4 => 'zKO395ntSd7AkJ',
        ];

        $records = [
            [
                'id' => 412,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '437X-XXXX-XXXX-X532',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-15 11:48:12',
                'updated_at' => '2025-08-15 11:48:12',
            ],
            [
                'id' => 414,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '464X-XXXX-XXXX-X834',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-15 12:10:53',
                'updated_at' => '2025-08-15 12:10:53',
            ],
            [
                'id' => 415,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '464X-XXXX-XXXX-X834',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-15 12:22:21',
                'updated_at' => '2025-08-15 12:22:21',
            ],
            [
                'id' => 416,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '464X-XXXX-XXXX-X834',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-15 12:38:37',
                'updated_at' => '2025-08-15 12:38:37',
            ],
            [
                'id' => 417,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '464X-XXXX-XXXX-X834',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-15 12:45:34',
                'updated_at' => '2025-08-15 12:45:34',
            ],
            [
                'id' => 422,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '372X-XXXX-XXX-001',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-18 17:43:34',
                'updated_at' => '2025-08-18 17:43:34',
            ],
            [
                'id' => 423,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '372X-XXXX-XXX-001',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-18 18:40:27',
                'updated_at' => '2025-08-18 18:40:27',
            ],
            [
                'id' => 544,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '220X-XXXX-XXXX-X843',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-20 12:37:35',
                'updated_at' => '2025-08-20 12:37:35',
            ],
            [
                'id' => 545,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '220X-XXXX-XXXX-X843',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-20 12:46:54',
                'updated_at' => '2025-08-20 12:46:54',
            ],
            [
                'id' => 546,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '403X-XXXX-XXXX-X528',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 08:07:39',
                'updated_at' => '2025-08-21 08:07:39',
            ],
            [
                'id' => 550,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '555X-XXXX-XXXX-X236',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 11:47:52',
                'updated_at' => '2025-08-21 11:47:52',
            ],
            [
                'id' => 551,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 11:52:13',
                'updated_at' => '2025-08-21 11:52:13',
            ],
            [
                'id' => 552,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 11:57:34',
                'updated_at' => '2025-08-21 11:57:34',
            ],
            [
                'id' => 553,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 12:08:37',
                'updated_at' => '2025-08-21 12:08:37',
            ],
            [
                'id' => 554,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 12:14:32',
                'updated_at' => '2025-08-21 12:14:32',
            ],
            [
                'id' => 556,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 13:00:09',
                'updated_at' => '2025-08-21 13:00:09',
            ],
            [
                'id' => 557,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '478X-XXXX-XXXX-X376',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-21 13:02:03',
                'updated_at' => '2025-08-21 13:02:03',
            ],
            [
                'id' => 558,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '027X-XXXX-XXXX-X005',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-22 08:08:54',
                'updated_at' => '2025-08-22 08:08:54',
            ],
            [
                'id' => 559,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '555X-XXXX-XXXX-X236',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-22 08:19:12',
                'updated_at' => '2025-08-22 08:19:12',
            ],
            [
                'id' => 560,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '555X-XXXX-XXXX-X236',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-22 08:27:27',
                'updated_at' => '2025-08-22 08:27:27',
            ],
            [
                'id' => 563,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '555X-XXXX-XXXX-X236',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-22 09:42:39',
                'updated_at' => '2025-08-22 09:42:39',
            ],
            [
                'id' => 564,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '027X-XXXX-XXXX-X005',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-23 12:55:41',
                'updated_at' => '2025-08-23 12:55:41',
            ],
            [
                'id' => 565,
                'merchant_key' => 'S5GRSOfPs9r9cYhj',
                'card_number_masked' => '027X-XXXX-XXXX-X005',
                'status' => 'success',
                'encrypted_data' => null,
                'scan_id' => null,
                'session_id' => null,
                'failure_reason' => null,
                'failure_stage' => null,
                'created_at' => '2025-08-23 13:00:09',
                'updated_at' => '2025-08-23 13:00:09',
            ],
        ];

        foreach ($records as &$record) {
            $userId = rand(1, 4);
            $record['user_id'] = $userId;
            $record['merchant_id'] = $merchantMapping[$userId];
        }
        unset($record); // break reference

        DB::table('scans')->insert($records);

        Schema::enableForeignKeyConstraints();
    }
}
