<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersSeeder extends Seeder
{
    /**
     * Seeder for the `users` table.
     * Generated on 2026-06-09 12:10:44 from users.csv
     * Total rows : 5
     * Chunk size : 500
     */
    public function run(): void
    {
        // Chunk 1 / 1
        DB::table('users')->insert([
            [
                'id' => 209,
                'service_type' => 'card_scan',
                'parent_id' => null,
                'merchant_id' => '4845925323992C4M',
                'email' => 'abebe@cashgousa.com',
                'country_code' => '+1',
                'country_name' => 'United States',
                'phone_number' => '7207669409',
                'aes_key' => 'y5fLQqHuWEJP5QJE',
                'otp_verified' => 0,
                'business_verified' => 'APPROVED',
                'verification_reason' => null,
                'on_trial' => 0,
                'trial_calls_remaining' => 20,
                'trial_ends_at' => '2026-01-12 14:58:05',
                'created_at' => '2026-01-05 14:58:05',
                'updated_at' => '2026-02-16 07:42:34',
                'role' => 'BUSINESS_USER',
                'device_id' => 'fda769bcad3132',
                'session_id' => 'session_1731024000_abc123',
                'device_timestamp' => null,
                'device' => '{brand": "samsung"',
                'network' => ' "model": "SM-S928B"',
                'sims' => ' "device": "e3q"',
                'location' => ' "sdkInt": 36',
            ],
            [
                'id' => 182,
                'service_type' => 'card_scan',
                'parent_id' => null,
                'merchant_id' => '93500624K6V95758',
                'email' => 'alim@ramadpay.com',
                'country_code' => '+1',
                'country_name' => 'United States',
                'phone_number' => '6128063203',
                'aes_key' => 'EmyzcZbMrCecjci6',
                'otp_verified' => 0,
                'business_verified' => 'APPROVED',
                'verification_reason' => null,
                'on_trial' => 0,
                'trial_calls_remaining' => 11,
                'trial_ends_at' => '2025-09-07 16:45:40',
                'created_at' => '2025-08-31 16:45:40',
                'updated_at' => '2025-09-08 11:34:49',
                'role' => 'BUSINESS_USER',
                'device_id' => null,
                'session_id' => null,
                'device_timestamp' => null,
                'device' => null,
                'network' => null,
                'sims' => null,
                'location' => null,
            ],
            [
                'id' => 150,
                'service_type' => 'card_scan',
                'parent_id' => null,
                'merchant_id' => 'mer000150',
                'email' => 'Dawood24@gmail.com',
                'country_code' => '+92',
                'country_name' => 'pakistan',
                'phone_number' => '3084352634',
                'aes_key' => 'S5GRSOfPs9r9cYhj',
                'otp_verified' => 0,
                'business_verified' => 'APPROVED',
                'verification_reason' => null,
                'on_trial' => 0,
                'trial_calls_remaining' => 10,
                'trial_ends_at' => '2025-08-22 09:23:33',
                'created_at' => '2025-08-15 09:23:33',
                'updated_at' => '2026-01-26 09:19:16',
                'role' => 'BUSINESS_USER',
                'device_id' => 'fda769bcad48d0d',
                'session_id' => 'session_1731024000_abc123d',
                'device_timestamp' => null,
                'device' => '{brand": "samsung"',
                'network' => ' "model": "SM-S928B"',
                'sims' => ' "device": "e3q"',
                'location' => ' "sdkInt": 36',
            ],
            [
                'id' => 173,
                'service_type' => 'card_scan',
                'parent_id' => null,
                'merchant_id' => 'G5536942984B2978',
                'email' => 'henrynoah790@gmail.com',
                'country_code' => '+1',
                'country_name' => 'United States',
                'phone_number' => '6464509293',
                'aes_key' => '7w3vINp1CqXN0Ng7',
                'otp_verified' => 0,
                'business_verified' => 'APPROVED',
                'verification_reason' => null,
                'on_trial' => 0,
                'trial_calls_remaining' => 999328,
                'trial_ends_at' => '2025-12-31 22:30:44',
                'created_at' => '2025-08-22 22:30:44',
                'updated_at' => '2026-06-09 03:38:43',
                'role' => 'BUSINESS_USER',
                'device_id' => '9214AD42-45DA-4034-80D4-459C44FEE12F',
                'session_id' => '3366807671',
                'device_timestamp' => null,
                'device' => '{brand": "Apple"',
                'network' => ' "model": "iPhone17',
                'sims' => '2"',
                'location' => ' "device": "iPhone17',
            ],
            [
                'id' => 206,
                'service_type' => 'card_scan',
                'parent_id' => null,
                'merchant_id' => '6O4584Y217268387',
                'email' => 'rahman@deeroservices.com',
                'country_code' => '+1',
                'country_name' => 'United States',
                'phone_number' => '9842698562',
                'aes_key' => 'FmYEmWS85phBfguh',
                'otp_verified' => 0,
                'business_verified' => 'APPROVED',
                'verification_reason' => null,
                'on_trial' => 0,
                'trial_calls_remaining' => 50,
                'trial_ends_at' => '2025-11-25 15:32:11',
                'created_at' => '2025-10-06 15:32:11',
                'updated_at' => '2026-06-09 10:27:36',
                'role' => 'BUSINESS_USER',
                'device_id' => 'sun',
                'session_id' => 'session_1731024000_abc123',
                'device_timestamp' => null,
                'device' => '{brand": "samsung"',
                'network' => ' "model": "SM-S938U"',
                'sims' => ' "device": "pa3q"',
                'location' => ' "sdkInt": 36',
            ],
        ]);
    }
}
